apiVersion: v1
kind: ServiceAccount
metadata:
  name: sl
  namespace: app-cjc
---
apiVersion: v1
kind: Service
metadata:
  name: sl
  namespace: app-cjc
spec:
  clusterIP: None
  selector:
    app: sl
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sl
  namespace: app-cjc
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: sl.cjc.cityapp.vx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sl
            port:
              number: 8080
  tls:
  - hosts:
    - sl.cjc.cityapp.vx
    secretName: sl-cert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sl
  namespace: app-cjc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sl
  template:
    metadata:
      labels:
        app: sl
    spec:
      serviceAccountName: sl
      containers:
      - name: app-cjc
        image: docker.io/joetanx/cityapp:php
        imagePullPolicy: IfNotPresent
        env:
        - name: DBADDR
          value: 127.0.0.1
        - name: DBUSER
          value: ''
        - name: DBPASS
          value: ''
      - name: secretless
        image: docker.io/cyberark/secretless-broker:latest
        imagePullPolicy: IfNotPresent
        args: ["-f", "/etc/secretless/sl-cm.yaml"]
        env:
        - name: JWT_TOKEN_PATH
          value: /var/run/secrets/tokens/jwt
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: apps-cm
        volumeMounts:
        - mountPath: /etc/secretless
          name: config
          readOnly: true
        - mountPath: /var/run/secrets/tokens
          name: jwt-token
      volumes:
      - name: jwt-token
        projected:
          sources:
          - serviceAccountToken:
              path: jwt
              expirationSeconds: 6000
              audience: https://apj-secrets.secretsmgr.cyberark.cloud/
      - name: config
        configMap:
          name: sl-cm